main: com.altoya.nationsrebuilt.App
name: nationsrebuilt
version: "1"
api-version: "1.20"
description: BLANK DESCRIPTION

commands:
  town:
    description: description
    usage: /command {var} {var}